### ISSUE TITLE
A question about double ship script landing

### ISSUE THREAD

**Issue by dyfxjtu** [CalebJ2/kOS-landing-script#1]
i'm working on the script landing of two rocket in the meantime. Your work is extremely prominent and help me so much. but when there are two ship, the kos cup can't occupy the Trajectories in the meantime and will report an error. Do you have some suggestion for that? thanks a lot！！！

**Comment by CalebJ2** [comment]
If I'm understanding this correctly, you can't access trajectories from the second vessel?

I think trajectories only calculates Trajectories for the active vessel. To get it to work for multiple vessels at the same time would probably require editing the Trajectories API and the kOS Trajectories addon.

This doesn't fix your problem but to avoid the error, always make sure TRAddon::HASIMPACT is true before accessing things like IMPACTPOS. If HASIMPACT returns true and it still gives an error for IMPACTPOS, that is a bug that would need to be fixed in kOS probably.

Something you could try as a workaround is to change the active vessel to the one you need to get the trajectory for. Although that might be too slow to be useful, not sure. http://ksp-kos.github.io/KOS_DOC/structures/misc/kuniverse.html#attribute:KUNIVERSE:ACTIVEVESSEL

It's been a long time since I worked on this stuff so I might be wrong about some of this.

**Comment by dyfxjtu** [comment]
Thanks a lot！！I have fix that problem！
